#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CircleImageCropper.Sample.Resource", IsApplication=true)]

namespace CircleImageCropper.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int showGuidelinesArray = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int textSize = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bkg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int butterfly = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sidewayssky = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int violetsky = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090008
			public const int Button_crop = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int Button_rotate = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int CropImageView = 2131296259;
			
			// aapt resource value: 0x7f09000a
			public const int action_settings = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int croppedImageView = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int mylayout = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int scrollview = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int showGuidelines = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int showGuidelinesLayout = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int showGuidelinesSpin = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int title = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int action_settings = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int aspectRatioX = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int aspectRatioXHeader = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int aspectRatioY = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int aspectRatioYHeader = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int crop = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int croppedImageDesc = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int fixedAspectRatio = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int rotate = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int showGuidelines = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int title = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int Mono_Android_Theme_Splash = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int RoboTheme = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
