#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CircleImageCropper.Resource", IsApplication=false)]

namespace CircleImageCropper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public static int showGuidelinesArray = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int aspectRatioX = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int aspectRatioY = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int fixAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int guidelines = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int imageResource = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public static int black_translucent = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public static int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int textSize = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int bkg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int butterfly = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int sidewayssky = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int violetsky = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040004
			public static int CropOverlayView = 2130968580;
			
			// aapt resource value: 0x7f040003
			public static int ImageView_image = 2130968579;
			
			// aapt resource value: 0x7f040002
			public static int off = 2130968578;
			
			// aapt resource value: 0x7f040000
			public static int on = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int onTouch = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int crop_image_view = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public static int action_settings = 2131165186;
			
			// aapt resource value: 0x7f070000
			public static int app_name = 2131165184;
			
			// aapt resource value: 0x7f070004
			public static int aspectRatioX = 2131165188;
			
			// aapt resource value: 0x7f070005
			public static int aspectRatioXHeader = 2131165189;
			
			// aapt resource value: 0x7f070006
			public static int aspectRatioY = 2131165190;
			
			// aapt resource value: 0x7f070007
			public static int aspectRatioYHeader = 2131165191;
			
			// aapt resource value: 0x7f070009
			public static int crop = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public static int croppedImageDesc = 2131165195;
			
			// aapt resource value: 0x7f070003
			public static int fixedAspectRatio = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public static int rotate = 2131165194;
			
			// aapt resource value: 0x7f070008
			public static int showGuidelines = 2131165192;
			
			// aapt resource value: 0x7f070001
			public static int title = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public static int AppBaseTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public static int AppTheme = 2131296257;
			
			// aapt resource value: 0x7f090002
			public static int RoboTheme = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CropImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 2
			public static int CropImageView_aspectRatioX = 2;
			
			// aapt resource value: 3
			public static int CropImageView_aspectRatioY = 3;
			
			// aapt resource value: 1
			public static int CropImageView_fixAspectRatio = 1;
			
			// aapt resource value: 0
			public static int CropImageView_guidelines = 0;
			
			// aapt resource value: 4
			public static int CropImageView_imageResource = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
